state_choices = {
  'Alborz': 'Alborz',
  'Ardabil': 'Ardabil',
  'Azerbaijan, East': 'Azerbaijan, East',
  'Azerbaijan, West': 'Azerbaijan, West',
  'Bushehr': 'Bushehr',
  'Chahar Mahaal and Bakhtiari': 'Chahar Mahaal and Bakhtiari',
  'Fars': 'Fars',
  'Gilan': 'Gilan',
  'Golestan': 'Golestan',
  'Hamadan': 'Hamadan',
  'Hormozgān': 'Hormozgān',
  'Ilam': 'Ilam',
  'Isfahan': 'Isfahan',
  'Kerman': 'Kerman',
  'Kermanshah': 'Kermanshah',
  'Khorasan, North': 'Khorasan, North',
  'Khorasan, Razavi': 'Khorasan, Razavi',
  'Khorasan, South': 'Khorasan, South',
  'Khuzestan': 'Khuzestan',
  'Kohgiluyeh and Boyer-Ahmad': 'Kohgiluyeh and Boyer-Ahmad',
  'Kurdistan': 'Kurdistan',
  'Lorestan': 'Lorestan',
  'Markazi': 'Markazi',
  'Mazandaran': 'Mazandaran',
  'Qazvin': 'Qazvin',
  'Qom': 'Qom',
  'Semnan': 'Semnan',
  'Sistan and Baluchestan': 'Sistan and Baluchestan',
  'Tehran': 'Tehran',
  'Yazd': 'Yazd',
  'Zanjan': 'Zanjan',
}

bedroom_choices= {
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  '6': 6,
  '7': 7,
  '8': 8,
  '9': 9,
  '10': 10,
}


price_choices= {
  "100": '$100',
  "200": '$200',
  "300": '$300',
  "400": '$400',
  "500": '$500',
  "600": '$600',
  "800": '$800',
  "1000":' $1000',
  "1200": '$1200',
  "1500": '$1500',
  "2000": '$2000',
}
  